### ISSUE TITLE
installation behind firewall fails because of wrong timestamp

### ISSUE THREAD

**Issue by vanilla-thunder** [openhab/openhabian#144]
when running openhab2 behind firewall (where some required ports are closed) it fails to sync date and time, so later when you are supposed to select UI on first start, it obviously fails to install ui addons because of wrong timestamp.
````2017-03-03 18:48:25.532 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0: [Could not transfer artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0 from/to openhab (https://dl.bintray.com/openhab/mvn/online-repo/2.0/): sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed]
java.io.IOException: Error resolving artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0: [Could not transfer artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0 from/to openhab (https://dl.bintray.com/openhab/mvn/online-repo/2.0/): sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:720)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:36)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)[8:org.apache.karaf.features.core:4.0.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705)[7:org.ops4j.pax.url.mvn:2.5.2]
	... 12 more
2017-03-03 18:48:25.598 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-basic, openhab-ui-habpanel, openhab-ui-paper': Error
````
  
maybe using some other time sync service with access on port 80, which should not be closed on any firewall,  would solve this issue.

**Comment by ThomDietrich** [comment]
Hey, sorry for the late reply. Were you able to solve this issue for you? To me this sounds like a problem unrelated to openHABian in the sense that it is way too specific to be of concern to the openHABian way. Please start a discussion with me if you disagree :)

**Comment by vanilla-thunder** [comment]
I had to manually set the date, time and reboot, so installation continued.

We literally run over 100 PCs behind our company's firewall including windows, linux, macs and other raspberries with regular raspbian.  None of them had ever problems getting date and time from the internet, openhabian is so far the one and only OS with this issue.
Since raspbian works, but openhabian not, it seems to be an openhabian-related problem to me. 

to be honest, I'm not even sure if getting time and date actually failed, i just know that UI installation fails at this point because of wrong date and time (actually i tried the whole instalklation process at least 3 times before checking logs, i can reproduce this problem every time).
It is not the typical issue, when something is not working at all, its more like "something is very unreliable and works only under particular circumstances".

**Comment by ThomDietrich** [comment]
You didn't say which hardware you are using. For the Raspberry Pi the (new) image is based on Raspbian, so there shouldn't be any issue with it. The old image was replaced because of problems just like the one here. Would you please test the Raspbian based image on your network?

**Comment by EliasGabrielsson** [comment]
It's hard to say exactly which effort to commit out of this more then the basic services need to be robust. Kind of fuel the reasons to even fix edge cases like this one: https://github.com/openhab/openhabian/issues/594

Closing this just for the reason of having a clean issue log
