### ISSUE TITLE
Frontail service fails to start

### ISSUE THREAD

**Issue by matteoraf** [openhab/openhabian#1460]
Looks like there's a typo [here](https://github.com/openhab/openhabian/blob/9b398a901036e49480177e297d2f5ca3fbac4d17/includes/frontail/frontail-preset.json#L20) preventing frontail to correctly load.

Simply adding a comma at the end of line 20 should fix it.

Output of systemctl status
```
openhabian@openhabian:/etc/systemd/system $ sudo systemctl status frontail.service 
 frontail.service - Frontail openHAB instance, reachable at http://openhabian:9001
   Loaded: loaded (/etc/systemd/system/frontail.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-02-10 00:12:22 CET; 5 days ago
     Docs: https://github.com/mthenw/frontail
  Process: 14058 ExecStart=/usr/lib/node_modules/frontail/bin/frontail --disable-usage-stats --ui-highlight --ui-highlight-preset /usr/lib/node_modules/frontail/preset/openhab.json --theme openhab --lines 2000 --number 200 /var/log/openhab/openhab.log /var/log
 Main PID: 14058 (code=exited, status=1/FAILURE)
```

Manually starting it returns this error:

```
undefined:21
    "ModelRepositoryImpl": "background-color: #a6cffd; font-weight: bold"
    ^

SyntaxError: Unexpected string in JSON at position 896
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/usr/lib/node_modules/frontail/index.js:114:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/frontail/bin/frontail:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

```

If you need to manually fix this error while waiting for the repo to update, you can 
`vi /usr/lib/node_modules/frontail/preset/openhab.json`

Dark theme isn't affected.

**Comment by hyzteric** [comment]
I tried the manual fix, it worked for me. Thanks.
