### ISSUE TITLE
comitup continuously restarting, using 40-50% cpu

### ISSUE THREAD

**Issue by AndyHowell** [openhab/openhabian#1556]
I trying to to a fresh installed on a pi3 with openhabian 1.6.5.

openhabian-pi-raspios32-v1.6.5.img.xz

From /var/log/daemon.log:

```
Jul 26 05:36:46 openhabian comitup[6256]: command failed: Operation not supported (-95)
Jul 26 05:36:47 openhabian comitup-web[6886]:  * Serving Flask app "web.comitupweb" (lazy loading)
Jul 26 05:36:47 openhabian comitup-web[6886]:  * Environment: production
Jul 26 05:36:47 openhabian comitup-web[6886]:    WARNING: Do not use the development server in a production environment.
Jul 26 05:36:47 openhabian comitup-web[6886]:    Use a production WSGI server instead.
Jul 26 05:36:47 openhabian comitup-web[6886]:  * Debug mode: off
Jul 26 05:36:48 openhabian comitup-web[6886]: Traceback (most recent call last):
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/sbin/comitup-web", line 11, in <module>
Jul 26 05:36:48 openhabian comitup-web[6886]:     load_entry_point('comitup==1.31', 'console_scripts', 'comitup-web')()
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/share/comitup/web/comitupweb.py", line 174, in main
Jul 26 05:36:48 openhabian comitup-web[6886]:     app.run(host="0.0.0.0", port=80, debug=False, threaded=True)
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 943, in run
Jul 26 05:36:48 openhabian comitup-web[6886]:     run_simple(host, port, self, **options)
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 814, in run_simple
Jul 26 05:36:48 openhabian comitup-web[6886]:     inner()
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 774, in inner
Jul 26 05:36:48 openhabian comitup-web[6886]:     fd=fd)
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 660, in make_server
Jul 26 05:36:48 openhabian comitup-web[6886]:     passthrough_errors, ssl_context, fd=fd)
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 577, in __init__
Jul 26 05:36:48 openhabian comitup-web[6886]:     self.address_family), handler)
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
Jul 26 05:36:48 openhabian comitup-web[6886]:     self.server_bind()
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
Jul 26 05:36:48 openhabian comitup-web[6886]:     socketserver.TCPServer.server_bind(self)
Jul 26 05:36:48 openhabian comitup-web[6886]:   File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
Jul 26 05:36:48 openhabian comitup-web[6886]:     self.socket.bind(self.server_address)
Jul 26 05:36:48 openhabian comitup-web[6886]: OSError: [Errno 98] Address already in use
Jul 26 05:36:50 openhabian systemd[1]: Reloading.
```
The install is over ethernet. I had wanted to use wifi. It seems that comitup ignore /boot/wpa_supplicant.conf and takes over the wifi interface.

**Comment by mstormi** [comment]
Sorry but without precise logs this is not useful as a bug report, can't even confirm it *is* a bug at all, in particular since you messed with system config files (if you do we won't provide support).
Restart from scratch, use the proper path to setup Wi-Fi (see openHABian docs, not some LInux resource), and take logs (debugmode=maximum). Then if you can reproduce the error and can provide the logs you can reopen this issue.
