### ISSUE TITLE
Add Javaoptions for 32 bit Raspi OS on 64bit kernel for Signal binding using sqlite

### ISSUE THREAD

**Issue by matmai** [openhab/openhabian#1915]
## Issue information:
With a new installation of openHABian v1.9.2 running Debian 12 (and also with my previous installation running Debian 11) the [Signal binding](https://community.openhab.org/t/signal-binding-4-0-0-0-5-0-0-0/138795) is not working.

This is caused by sqlite that is used by the Signal binding because it does not detect the used architecture correctly.

Adding the option `-Dorg.sqlite.osinfo.architecture=armv7` to `EXTRA_JAVA_OPTS` in the file `/etc/defaults/openhab` and reinstalling the binding makes it work.

It is only needed if `uname -m` returns _aarch64_ while `getconf LONG_BIT` returns _32_.

My suggestion is to add the option as a workaround into openhabian to increase the usabilty. Probably [openhab.bash](https://github.com/openhab/openhabian/blob/63231be50191c478c5e3ce87b0abf02ee378b8d9/functions/openhab.bash#L232) would be a place to add it.

For details see: https://community.openhab.org/t/openhab-installs-64-bit-jni-lib-on-32-bit-raspberry-pi-and-breaks-jdbc-sqlite/151051/3

## Debug information:
If the option is not set the binding throws the following error:
```
[WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Error opening connection
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80) ~[?:?]
	at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:104) ~[?:?]
	at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:33) ~[?:?]
	at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:43) ~[?:?]
	at org.asamk.signal.manager.storage.SignalAccount.lambda$31(SignalAccount.java:1275) ~[?:?]
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1735) ~[?:?]
	at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1273) ~[?:?]
	at org.asamk.signal.manager.storage.SignalAccount.lambda$14(SignalAccount.java:1239) ~[?:?]
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1735) ~[?:?]
	at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1235) ~[?:?]
	at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:32) ~[?:?]
	at org.asamk.signal.manager.storage.SignalAccount.init(SignalAccount.java:367) ~[?:?]
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:201) ~[?:?]
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:97) ~[?:?]
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:84) ~[?:?]
	at org.openhab.binding.signal.internal.protocol.SignalService.start(SignalService.java:150) ~[?:?]
	at org.openhab.binding.signal.internal.handler.SignalBridgeHandler.checkAndStartServiceIfNeeded(SignalBridgeHandler.java:166) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:283) ~[?:?]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67) ~[?:?]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[?:?]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19) ~[?:?]
	at org.sqlite.JDBC.createConnection(JDBC.java:104) ~[?:?]
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:464) ~[?:?]
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:456) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550) ~[?:?]
	... 24 more
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64:/var/lib/openhab/tmp/lib]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:363) ~[?:?]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:72) ~[?:?]
	at org.sqlite.core.NativeDB.load(NativeDB.java:67) ~[?:?]
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280) ~[?:?]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67) ~[?:?]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[?:?]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19) ~[?:?]
	at org.sqlite.JDBC.createConnection(JDBC.java:104) ~[?:?]
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:464) ~[?:?]
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:456) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550) ~[?:?]
	... 24 more
```

## System information:
openHABian v1.9.2

`uname -m`: "aarch64"

`cat /etc/os-release` :
```
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by mstormi** [comment]
The proper fix
A non-official marketplace-only binding that very few users use to require some obscure java settings on only some specific hardware-OS combo due to some sort of improper library being compiled with _really, really_ is a niche thing.
Will not be working around that in openHABian let alone based on 1 yr old information.

If you're affected you can easily edit EXTRA_JAVA_OPTS on your system.
