### ISSUE TITLE
[MQTT] Too many publishes in progress

### ISSUE THREAD

**Issue by CRASH-Tech** [openhab/openhabian#395]
Some time I have this error:

mqtt.conf:
```
openhabian.url=tcp://127.0.0.1:1883
openhabian.clientId=OpenHAB
openhabian.user=user
openhabian.pwd=password
openhabian.qos=2
openhabian.retain=true
openhabian.async=true
```

mosquitto.conf
```
pid_file /var/run/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/
log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
password_file /etc/mosquitto/passwd
allow_anonymous false
max_connections -1
max_inflight_messages 0 //Trying to fix error
max_queued_messages 1000 //Trying to fix error
```

Logs:
```
2018-05-16 00:58:02.031 [ERROR] [g.mqtt.internal.MqttMessagePublisher] - Error publishing...
org.eclipse.paho.client.mqttv3.MqttException: Too many publishes in progress
        at org.eclipse.paho.client.mqttv3.internal.ClientState.send(ClientState.java:496) [202:org.openhab.io.transport.mqtt:1.11.0]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.internalSend(ClientComms.java:132) [202:org.openhab.io.transport.mqtt:1.11.0]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:156) [202:org.openhab.io.transport.mqtt:1.11.0]
        at org.eclipse.paho.client.mqttv3.MqttTopic.publish(MqttTopic.java:107) [202:org.openhab.io.transport.mqtt:1.11.0]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection$2.publish(MqttBrokerConnection.java:426) [202:org.openhab.io.transport.mqtt:1.11.0]
        at org.openhab.binding.mqtt.internal.MqttMessagePublisher.publish(MqttMessagePublisher.java:175) [200:org.openhab.binding.mqtt:1.11.0]
        at org.openhab.binding.mqtt.internal.MqttEventBusBinding.receiveCommand(MqttEventBusBinding.java:136) [200:org.openhab.binding.mqtt:1.11.0]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:45) [201:org.openhab.core.compat1x:2.2.0]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:82) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by ThomDietrich** [comment]
Please provide a clear description of the issue, when it occurs and what you've tried and learned so far.

That said, this is not a openHABian issue but rather a problem with your setup or environment. I'd suggest to contact the openHAB community forum! Good luck!
