### ISSUE TITLE
frontail not installing

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#578]
ok this is special as I've seen this happen in the Travis build context (only?)
I think though that first-boot/openhabian-setup shouldn't terminate then.

2019-06-23_16:21:44_UTC [openHABian] Installing the openHAB Log Viewer (frontail)... 
$ npm install -g frontail 
Error: could not get uid/gid
[ 'nobody', 0 ]
    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:77:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:225:22)
    at /usr/lib/node_modules/npm/lib/npm.js:263:24
    at /usr/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:173:20)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:98
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^
TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
FAILED (frontail)
2019-06-23_16:21:48_UTC [openHABian] Initial setup exiting with an error!
The command '/bin/sh -c bash /opt/openhabian/build-image/first-boot.bash' returned a non-zero code: 1

**Comment by EliasGabrielsson** [comment]
Hmm.
Yea, we better check it out. The testing pipeline is far from perfect.

**Comment by mstormi** [comment]
I've changed the pipeline and added install/upgrade of the npm binary which failed here. Now install proceeds. It errors at the after frontail service restart but that's a different issue then.
[See build log](https://travis-ci.com/mstormi/openhabian/builds/117032457)
So I think this was due to a bad intermediary state or version of npm and we can close this issue.

BTW: I also tried with a buster image [see build log](https://travis-ci.com/mstormi/openhabian/builds/117033623)
The build system is cool ;-)

**Comment by mstormi** [comment]
I trying our build/testing system using a buster base image for RPi to run build.bash 

As can be seen [here (line 2319ff, I have inserted "set -x" to display what build.bash is doing)](https://travis-ci.com/mstormi/openhabian/builds/121088349), frontail package install will not create the directories that the build.bash script wants to put config files into.
I'm not sure how to handle this. Did frontail recently change its file location or are these dirs missing because of the difference from stretch to buster or eventually due to lack of systemd in balenalibs image ?
I'm not familiar with frontail. @EliasGabrielsson @ThomDietrich any idea?
Build sources such as Dockerfile.openhabian are [here](https://github.com/mstormi/openhabian/tree/build).

**Comment by mstormi** [comment]
Fixed/superseded by #609 .
